{% set versions = {
    "2.0" : "ff8971c7f9b6074c97ac9c98d66aca494b0b76f0ba2962267c0bd8406d1524ed"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "hathor")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace('/', '.')|replace('-', '.') }}

source:
  url: "https://www.physik.hu-berlin.de/de/pep/tools/Hathor-{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}
  patches:
    - patches/makefiles.patch

requirements:
  build:
    - {{ compiler('gfortran') }}   # GNU Fortran compiler
    - {{ compiler('c') }}          # GNU C compiler
    - {{ compiler('cxx') }}        # GNU C++ compiler
    
    - cmake                        # Build system
    - make                         # Make utility

  host:
    - lhapdf

  run:
    - lhapdf

about:
  home: "https://www.physik.hu-berlin.de/de/pep/tools/hathor.html"
  license: "GPL-3.0"
  summary: "HAdronic Top and Heavy quarks crOss section calculatoR."

extra:
  recipe-maintainers:
    - meiyasan
